version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: doadmin
  MYSQL_PORT: 25060
  MYSQL_PASSWORD: whej5edxdyubz1xe
  MYSQL_DATABASE: defaultdb
  REACT_APP_SERVER_PORT: 8000
  MYSQL_HOST_IP: db-mysql-blr1-07157-do-user-9121984-0.b.db.ondigitalocean.com
  MYSQL_SSLMODE: REQUIRED

services:
  server:
    build: ./server
    expose:
      - 8000
    environment:
      <<: *common-variables
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app/
      - ./server/node_modules:/usr/src/app/node_modules
    command: npm start
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/src/app/
      - ./client/node_modules:/usr/src/app/node_modules
    links:
      - server
    command:
     - /usr/src/app/entrypoint.sh
  python:
    build: ./python
    ports:
      - "5000:5000"
    environment:
      <<: *common-variables
    volumes:
      - ./python:/app
