/**
 * Created by shashi.sh on 17/04/21.
 */

export const LOAD_RVOL_DATA = 'LOAD_RVOL_DATA';
export const LOAD_RVOL_DATA_SUCCESS = 'LOAD_RVOL_DATA_SUCCESS';
export const LOAD_RVOL_DATA_FAIL = 'LOAD_RVOL_DATA_FAIL';

export const LOAD_CONFIG_DATA = 'LOAD_CONFIG_DATA';
export const LOAD_CONFIG_DATA_FAIL = 'LOAD_CONFIG_DATA_FAIL';
export const LOAD_CONFIG_DATA_SUCCESS = 'LOAD_CONFIG_DATA_SUCCESS';