baseLoginUrl = "https://kite.trade/connect/login"
password = "ankush1234"
pin = "434258"
apiKey = "kejb8tewdr6kk1bn"
userId = "HX5564"
apiSecret = "fdcl73by8psacinfxszkfhanv7t9ogb7"
url = baseLoginUrl + "?api_key=" + apiKey + "&v=3"
user_id_xpath = "//*[@id=\"container\"]/div/div/div[2]/form/div[1]/input"
password_xpath = "//*[@id=\"container\"]/div/div/div[2]/form/div[2]/input"
submit_xpath = "//*[@id=\"container\"]/div/div/div[2]/form/div[4]/button"
pin_xpath = "//*[@id=\"container\"]/div/div/div[2]/form/div[2]/div/input"
continue_xpath = "//*[@id=\"container\"]/div/div/div[2]/form/div[3]/button"